/**
 * Event types for the research probe event logging system.
 */
export const EventTypes = Object.freeze({
  // Playback events
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SEEK: 'SEEK',
  SEGMENT_ENTER: 'SEGMENT_ENTER',

  // Description events
  DESCRIPTION_LEVEL_CHANGE: 'DESCRIPTION_LEVEL_CHANGE',
  DESCRIPTION_VIEWED: 'DESCRIPTION_VIEWED',
  DESCRIPTION_SPOKEN: 'DESCRIPTION_SPOKEN',
  DESCRIPTION_FLAGGED: 'DESCRIPTION_FLAGGED',

  // VQA events
  VQA_QUESTION: 'VQA_QUESTION',
  VQA_ANSWER: 'VQA_ANSWER',

  // Edit events
  EDIT_ACTION: 'EDIT_ACTION',
  TRIM: 'TRIM',
  SPLIT: 'SPLIT',
  REORDER: 'REORDER',
  DELETE_CLIP: 'DELETE_CLIP',
  ADD_CAPTION: 'ADD_CAPTION',
  REMOVE_CAPTION: 'REMOVE_CAPTION',
  EDIT_CAPTION: 'EDIT_CAPTION',
  UNDO: 'UNDO',
  REDO: 'REDO',
  IMPORT_VIDEO: 'IMPORT_VIDEO',

  // Exploration mode events (Probe 1)
  ENTER_EXPLORATION: 'ENTER_EXPLORATION',
  EXIT_EXPLORATION: 'EXIT_EXPLORATION',
  NAVIGATE_SEGMENT: 'NAVIGATE_SEGMENT',
  CHANGE_GRANULARITY: 'CHANGE_GRANULARITY',
  PLAY_SUMMARY: 'PLAY_SUMMARY',

  // Handover events (Probe 2)
  HANDOVER_INITIATED: 'HANDOVER_INITIATED',
  INTENT_LOCKED: 'INTENT_LOCKED',
  HANDOVER_COMPLETED: 'HANDOVER_COMPLETED',
  HELPER_ACTION: 'HELPER_ACTION',
  HANDOVER_SUGGESTION_SHOWN: 'HANDOVER_SUGGESTION_SHOWN',
  HANDOVER_SUGGESTION_ACCEPTED: 'HANDOVER_SUGGESTION_ACCEPTED',
  HANDOVER_SUGGESTION_DISMISSED: 'HANDOVER_SUGGESTION_DISMISSED',
  RECORD_VOICE_NOTE: 'RECORD_VOICE_NOTE',
  DELETE_MARK: 'DELETE_MARK',
  HANDOVER_TASKS: 'HANDOVER_TASKS',
  HANDOVER_LIVE: 'HANDOVER_LIVE',
  COMPLETE_TASK: 'COMPLETE_TASK',
  PLAY_VOICE_NOTE: 'PLAY_VOICE_NOTE',

  // Text overlay (Probe 2 & 3 helper)
  ADD_TEXT_OVERLAY: 'ADD_TEXT_OVERLAY',
  MOVE_TEXT_OVERLAY: 'MOVE_TEXT_OVERLAY',
  REMOVE_TEXT_OVERLAY: 'REMOVE_TEXT_OVERLAY',
  EDIT_TEXT_OVERLAY: 'EDIT_TEXT_OVERLAY',

  // Device events (Probe 3)
  DEVICE_CONNECTED: 'DEVICE_CONNECTED',
  DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',
  SYNC_EVENT: 'SYNC_EVENT',

  // Communication
  MESSAGE_SENT: 'MESSAGE_SENT',

  // Session events
  SESSION_START: 'SESSION_START',
  SESSION_END: 'SESSION_END',
  CONDITION_START: 'CONDITION_START',
  CONDITION_END: 'CONDITION_END',

  // Accessibility events
  TEXT_SIZE_CHANGE: 'TEXT_SIZE_CHANGE',
  CONTRAST_TOGGLE: 'CONTRAST_TOGGLE',
  AUDIO_TOGGLE: 'AUDIO_TOGGLE',
  SPEECH_RATE_CHANGE: 'SPEECH_RATE_CHANGE',
});

/**
 * Actor identifiers for event attribution.
 */
export const Actors = Object.freeze({
  CREATOR: 'CREATOR',
  HELPER: 'HELPER',
  AI: 'AI',
  RESEARCHER: 'RESEARCHER',
  SYSTEM: 'SYSTEM',
});
