/**
 * Event types for the research probe event logging system.
 */
export const EventTypes = Object.freeze({
  // Playback events
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SEEK: 'SEEK',
  SEGMENT_ENTER: 'SEGMENT_ENTER',

  // Description events
  DESCRIPTION_LEVEL_CHANGE: 'DESCRIPTION_LEVEL_CHANGE',
  DESCRIPTION_VIEWED: 'DESCRIPTION_VIEWED',
  DESCRIPTION_SPOKEN: 'DESCRIPTION_SPOKEN',
  DESCRIPTION_FLAGGED: 'DESCRIPTION_FLAGGED',

  // VQA events
  VQA_QUESTION: 'VQA_QUESTION',
  VQA_ANSWER: 'VQA_ANSWER',

  // Edit events
  EDIT_ACTION: 'EDIT_ACTION',
  TRIM: 'TRIM',
  SPLIT: 'SPLIT',
  REORDER: 'REORDER',
  DELETE_CLIP: 'DELETE_CLIP',
  ADD_CAPTION: 'ADD_CAPTION',
  REMOVE_CAPTION: 'REMOVE_CAPTION',
  EDIT_CAPTION: 'EDIT_CAPTION',
  UNDO: 'UNDO',
  REDO: 'REDO',
  IMPORT_VIDEO: 'IMPORT_VIDEO',

  // Exploration mode events (Probe 1)
  ENTER_EXPLORATION: 'ENTER_EXPLORATION',
  EXIT_EXPLORATION: 'EXIT_EXPLORATION',
  NAVIGATE_SEGMENT: 'NAVIGATE_SEGMENT',
  CHANGE_GRANULARITY: 'CHANGE_GRANULARITY',
  PLAY_SUMMARY: 'PLAY_SUMMARY',

  // Handover events (Probe 2)
  HANDOVER_INITIATED: 'HANDOVER_INITIATED',
  HANDOVER_CANCELLED: 'HANDOVER_CANCELLED',
  INTENT_LOCKED: 'INTENT_LOCKED',
  HANDOVER_COMPLETED: 'HANDOVER_COMPLETED',
  HELPER_ACTION: 'HELPER_ACTION',
  HANDOVER_SUGGESTION_SHOWN: 'HANDOVER_SUGGESTION_SHOWN',
  HANDOVER_SUGGESTION_ACCEPTED: 'HANDOVER_SUGGESTION_ACCEPTED',
  HANDOVER_SUGGESTION_DISMISSED: 'HANDOVER_SUGGESTION_DISMISSED',
  RECORD_VOICE_NOTE: 'RECORD_VOICE_NOTE',
  DELETE_MARK: 'DELETE_MARK',
  HANDOVER_TASKS: 'HANDOVER_TASKS',
  HANDOVER_LIVE: 'HANDOVER_LIVE',
  COMPLETE_TASK: 'COMPLETE_TASK',
  PLAY_VOICE_NOTE: 'PLAY_VOICE_NOTE',

  // Control lock (Probes 2b, 3) — see ControlLockBanner.
  CONTROL_TAKEN: 'CONTROL_TAKEN',

  // Text overlay (Probe 2 & 3 helper)
  ADD_TEXT_OVERLAY: 'ADD_TEXT_OVERLAY',
  MOVE_TEXT_OVERLAY: 'MOVE_TEXT_OVERLAY',
  REMOVE_TEXT_OVERLAY: 'REMOVE_TEXT_OVERLAY',
  EDIT_TEXT_OVERLAY: 'EDIT_TEXT_OVERLAY',

  // Device events (Probe 3)
  DEVICE_CONNECTED: 'DEVICE_CONNECTED',
  DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',
  SYNC_EVENT: 'SYNC_EVENT',

  // Communication
  MESSAGE_SENT: 'MESSAGE_SENT',

  // Session events
  SESSION_START: 'SESSION_START',
  SESSION_END: 'SESSION_END',
  CONDITION_START: 'CONDITION_START',
  CONDITION_END: 'CONDITION_END',

  // Accessibility events
  TEXT_SIZE_CHANGE: 'TEXT_SIZE_CHANGE',
  CONTRAST_TOGGLE: 'CONTRAST_TOGGLE',
  AUDIO_TOGGLE: 'AUDIO_TOGGLE',
  SPEECH_RATE_CHANGE: 'SPEECH_RATE_CHANGE',

  // Editor (used in existing code but was missing from enum)
  OPEN_EDITOR: 'OPEN_EDITOR',

  // Task routing (Probe 2b & Probe 3 Layer 3)
  TASK_ROUTE_SELF: 'TASK_ROUTE_SELF',
  TASK_ROUTE_AI: 'TASK_ROUTE_AI',
  TASK_ROUTE_HELPER: 'TASK_ROUTE_HELPER',
  AI_EDIT_RESPONSE: 'AI_EDIT_RESPONSE',
  AI_EDIT_APPLIED: 'AI_EDIT_APPLIED',
  HELPER_TASK_RECEIVED: 'HELPER_TASK_RECEIVED',
  HELPER_TASK_STATUS: 'HELPER_TASK_STATUS',
  AI_EDIT_REVIEWED: 'AI_EDIT_REVIEWED',
  AI_EDIT_UNDONE: 'AI_EDIT_UNDONE',

  // Phase transition (2a → 2b)
  PHASE_TRANSITION_2A_TO_2B: 'PHASE_TRANSITION_2A_TO_2B',
  PROJECT_STATE_EXPORT: 'PROJECT_STATE_EXPORT',

  // Helper fallback (Probe 1)
  HELPER_FALLBACK: 'HELPER_FALLBACK',

  // AI Suggestion system (Probe 3)
  SUGGESTION_DEPLOYED: 'SUGGESTION_DEPLOYED',
  SUGGESTION_DISMISSED: 'SUGGESTION_DISMISSED',
  SUGGESTION_NOTED: 'SUGGESTION_NOTED',
  SUGGESTION_ROUTED: 'SUGGESTION_ROUTED',
  SUGGESTION_ROUTE_SELF: 'SUGGESTION_ROUTE_SELF',
  SUGGESTION_ROUTE_AI: 'SUGGESTION_ROUTE_AI',
  SUGGESTION_ROUTE_HELPER: 'SUGGESTION_ROUTE_HELPER',
  HELPER_SUGGESTION_RESPONSE: 'HELPER_SUGGESTION_RESPONSE',
  SUGGESTION_CHAIN_COMPLETE: 'SUGGESTION_CHAIN_COMPLETE',

  // Scene block navigation (v2.1)
  SCENE_BLOCK_EXPAND: 'SCENE_BLOCK_EXPAND',
  SCENE_BLOCK_COLLAPSE: 'SCENE_BLOCK_COLLAPSE',
  PLAY_ALL_START: 'PLAY_ALL_START',
  PLAY_ALL_STOP: 'PLAY_ALL_STOP',

  // Scene editing actions (v2.1)
  KEEP_SCENE: 'KEEP_SCENE',
  DISCARD_SCENE: 'DISCARD_SCENE',
  ADD_VOICE_NOTE: 'ADD_VOICE_NOTE',
  AI_EDIT_PROPOSED: 'AI_EDIT_PROPOSED',
  AI_EDIT_ACCEPTED: 'AI_EDIT_ACCEPTED',
  AI_EDIT_CANCELLED: 'AI_EDIT_CANCELLED',

  // Helper visual tools (v2.1)
  COLOUR_ADJUST: 'COLOUR_ADJUST',
  FRAMING_CHANGE: 'FRAMING_CHANGE',
  AWARENESS_VIEWED: 'AWARENESS_VIEWED',
});

/**
 * Actor identifiers for event attribution.
 */
export const Actors = Object.freeze({
  CREATOR: 'CREATOR',
  HELPER: 'HELPER',
  AI: 'AI',
  RESEARCHER: 'RESEARCHER',
  SYSTEM: 'SYSTEM',
});
